### ISSUE TITLE
运行时出现的问题

### ISSUE THREAD

**Issue by rdsuncn** [heiher/gst-amc-sink#2]
您好，试用了您的amcsink，在安卓上运行时出现这样的错误，请教一下是什么原因呢。
E/GStreamer+GST_PIPELINE(4909): 1:28:13.111364002 0xed8aa2e0 ./grammar.y:672:priv_gst_parse_yyparse no element "amcvideosink"

**Comment by heiher** [comment]
可能是 ndk 里没有链接这个模块。

**Comment by rdsuncn** [comment]
非常感谢您的回答。成功编译了amcsink这个静态库，但是编译mcplayer的时候出错了。google了一遍找不到头绪，希望大神帮我看看问题出在哪里。

Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 16 in /home/suntu/mcplayer/AndroidManifest.xml    
GStreamer      : [GEN] => gst-build-armeabi-v7a/gstreamer_android.c
GStreamer      : [COMPILE] => gst-build-armeabi-v7a/gstreamer_android.c
GStreamer      : [LINK] => gst-build-armeabi-v7a/libgstreamer_android.so
/home/suntu/android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld.gold: **error: cannot find -lgstamcsink**
gst-build-armeabi-v7a/gstreamer_android.o:gstreamer_android.c:function gst_android_register_static_plugins: error: undefined reference to 'gst_plugin_amcsink_register'
collect2: error: ld returned 1 exit status
make: *** [buildsharedlibrary_armeabi-v7a] Error 1

主要就是cannot find -lgstamcsink这个错误。
我的环境如下，os是ubuntu，ndk r10d, gstream是gstreamer-1.0-android-universal-1.12.2

Android,mk如下
`GSTREAMER_ROOT_ANDROID := /home/suntu/gstreamer-1.0-android-universal-1.12.2/armv7
LOCAL_PATH := $(call my-dir)

#
include $(CLEAR_VARS)
LOCAL_MODULE := amcsink_lib
LOCAL_SRC_FILES := amcsink/libgstamcsink_armv7.a
LOCAL_EXPORT_C_INCLUDES := amcsink/include
include $(PREBUILT_STATIC_LIBRARY)
#

include $(CLEAR_VARS)

LOCAL_MODULE    := mcplayer
LOCAL_SRC_FILES := core.c
LOCAL_STATIC_LIBRARIES := amcsink_lib
LOCAL_SHARED_LIBRARIES := gstreamer_android
LOCAL_LDLIBS := -landroid
#LOCAL_LDLIBS := -landroid -lgstamcsink
#LOCAL_LDLIBS += -L$amcsink/ -landroid
include $(BUILD_SHARED_LIBRARY)

ifndef GSTREAMER_ROOT
ifndef GSTREAMER_ROOT_ANDROID
$(error GSTREAMER_ROOT_ANDROID is not defined!)
endif
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)
endif
GSTREAMER_NDK_BUILD_PATH  := $(GSTREAMER_ROOT)/share/gst-android/ndk-build/
include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS         := $(GSTREAMER_PLUGINS_CORE) $(GSTREAMER_PLUGINS_PLAYBACK) $(GSTREAMER_PLUGINS_NET) $(GSTREAMER_PLUGINS_SYS) mpegtsdemux videoparsersbad amcsink
G_IO_MODULES              := gnutls
include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk`

**Comment by rdsuncn** [comment]
搞定了，用静态链接，那下面amcsink就不需要了

**Comment by rdsuncn** [comment]
大神，可以的话，有一些方面的合作能够洽谈一下么。这是我的联系方式 rdsuncn@163.com，希望得到您的回应
